// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7qwMHfjMlgRljH0BkhbBzPjQFafGkPoQ',
    appId: '1:229581752328:web:215ef622678f7b35ffe9bd',
    messagingSenderId: '229581752328',
    projectId: 'hifazat-b4c71',
    authDomain: 'hifazat-b4c71.firebaseapp.com',
    storageBucket: 'hifazat-b4c71.firebasestorage.app',
    measurementId: 'G-3C5KXY79KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4r3yp9DQ4HSj9WqnJFvAK8ZHKLV_LFf8',
    appId: '1:229581752328:android:5be589ca8aa019c2ffe9bd',
    messagingSenderId: '229581752328',
    projectId: 'hifazat-b4c71',
    storageBucket: 'hifazat-b4c71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr3wh7srO9M5cXRx3DCgLl1AWhKTFeVqw',
    appId: '1:229581752328:ios:5299fecfa7d460fdffe9bd',
    messagingSenderId: '229581752328',
    projectId: 'hifazat-b4c71',
    storageBucket: 'hifazat-b4c71.firebasestorage.app',
    iosBundleId: 'com.example.hifazat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCr3wh7srO9M5cXRx3DCgLl1AWhKTFeVqw',
    appId: '1:229581752328:ios:5299fecfa7d460fdffe9bd',
    messagingSenderId: '229581752328',
    projectId: 'hifazat-b4c71',
    storageBucket: 'hifazat-b4c71.firebasestorage.app',
    iosBundleId: 'com.example.hifazat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7qwMHfjMlgRljH0BkhbBzPjQFafGkPoQ',
    appId: '1:229581752328:web:5fa5f06546043884ffe9bd',
    messagingSenderId: '229581752328',
    projectId: 'hifazat-b4c71',
    authDomain: 'hifazat-b4c71.firebaseapp.com',
    storageBucket: 'hifazat-b4c71.firebasestorage.app',
    measurementId: 'G-WZY0Q79H2Z',
  );

}